steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/relief-pharmacist-scheduler/scheduler-nest-api', '.']

  # Step 2: Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/relief-pharmacist-scheduler/scheduler-nest-api']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'scheduler-nest-api',
        '--image', 'gcr.io/relief-pharmacist-scheduler/scheduler-nest-api',
        '--region', 'us-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--add-cloudsql-instances', 'relief-pharmacist-scheduler:us-west1:relief-pharm-staging-db',
        '--set-env-vars', 'NODE_ENV=staging',
        '--set-secrets', 'DATABASE_URL=projects/353576862326/secrets/DATABASE_URL:latest',
        '--set-secrets', 'FIREBASE_PRIVATE_KEY=projects/353576862326/secrets/FIREBASE_PRIVATE_KEY:latest',
        '--set-secrets', 'FIREBASE_CLIENT_EMAIL=projects/353576862326/secrets/FIREBASE_CLIENT_EMAIL:latest',
        '--set-secrets', 'FIREBASE_PROJECT_ID=projects/353576862326/secrets/FIREBASE_PROJECT_ID:latest',
        #'--set-env-vars', 'PORT=8080'
      ]

images:
  - 'gcr.io/relief-pharmacist-scheduler/scheduler-nest-api'
 

  
