#Dockerfile used to build devcontainer
FROM mcr.microsoft.com/mirror/docker/library/node:20-bookworm-slim

# Only use this for OS-level libs your specific app needs to compile/run
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install git